[workspace]
members = ["lib", "bindings"]
resolver = "3"

[workspace.dependencies]
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.19" }
tokio = { version = "1.44.1" }
tokio-util = { version = "0.7.14" }
derive_more = { version = "1.0.0" }
